### PR TITLE
Libluasocket support

### PR DESCRIPTION
**Pull request by brainrom**
Provides network functionalities. 
To build on android ndk requires some changes in lua5.0->lua5.1 compat layer, but finally it works.

### CODE REVIEW

**Comment by bjornbytes** [comment]
It's cool to finally have this working.

Did you forget to add the `src/lib/luasocket` sources?

Either way, I don't think I will be merging this PR, because there is a fancy new plugin system that should allow this to be easily added to builds.  Plugins are currently on the `dev` branch, and I haven't documented them yet.  But the main workflow is to make a `plugins` folder in the repo root and copy/clone/submodule plugins into there.  Plugins are regular repositories with CMakeLists in them.  Here are 3 examples of plugins: [`bjornbytes/lua-cjson`](https://github.com/bjornbytes/lua-cjson), [`bjornbytes/lua-enet`](https://github.com/bjornbytes/lua-enet), [`bjornbytes/lua-deepspeech`](https://github.com/bjornbytes/lua-eepspeech).  Most of the time no changes need to be made to make stuff compatible as lovr plugins.  Let me know if I can help out with the process.

**Comment by brainrom** [comment]
I tried to build libluasocket independently, but it heavily depend on lua machine, almost all protocol-specific code are written on lua and I haven't found another solution, than just compile it with the engine itself.

**Comment by bjornbytes** [comment]
When built as a lovr plugin it will automatically have access to the Lua headers/libraries

**Comment by brainrom** [comment]
@bjornbytes 
> Let me know if I can help out with the process.
Now I'm trying to rebuild it as LOVR [plugin](https://github.com/brainrom/lovr-luasocket), but encountered a problem (Error: no module 'luasocket.http' in file ./luasocket.so) to define submodules inside single .so/.dll file. AFAIK I should change luasocket.c someway to define all it's submodules but currently I can't figure out how exactly. Help is welcome.

**Comment by brainrom** [comment]
So, with some workarounds now it can works. The final question is how to avoid symlinking libraries.

**Comment by bjornbytes** [comment]
That is very cool.  So it looks like luasocket is using the "all-in-one" approach documented in [Lua's manual](https://www.lua.org/manual/5.1/manual.html#pdf-package.loaders), and lovr.filesystem's native library loader doesn't support that yet.  I can look into adding support for it, it would help match the functionality of Lua's built-in loader.

**Comment by brainrom** [comment]
> (Implementation question I'm thinking about: Should it be a new loader that gets added or could it somehow be integrated into the existing one?)

Where it's located? AFAIU all loaders are placced inside `api/l_filesystem.c` and on line 429 metioned, that lovr should search native libraries next to executable, but instead of it, lovr search it in `pwd`. So, I think it's a bug.

**Pull request closed without merging**
