### PR TITLE
Phonon/SteamAudio support in CMake build

### PR DESCRIPTION
**Pull request by mcclure**
I tested this PR but only on Windows.

### CODE REVIEW

**Comment by bjornbytes** [comment]
I think the 32 bit versions could be removed

**Comment by mcclure** [comment]
I could do that. Do we know for a fact armv7 headsets are dead tho?

**Comment by bjornbytes** [comment]
There isn't one officially supported by lovr.  32 bit is also generally decrepit in terms of optimization/testing here

**Comment by mcclure** [comment]
Okay. All platforms including Windows? We're supporting 32 bit Windows for OculusAudio.

**Comment by bjornbytes** [comment]
Yeah, same for windows

**Comment by mcclure** [comment]
Removed 32-bit support

**Pull request merged**
