### PR TITLE
Submo's for VR SDKs, and other changes (rebased)

### PR DESCRIPTION
**Pull request by nevyn**
This is https://github.com/bjornbytes/lovr/pull/398 but with squashed fixups and rebased linearly onto latest dev.

### CODE REVIEW

**Comment by nevyn** [comment]
@bjornbytes hmm. Perhaps I should try to disable LFS for the submos and push again so we're not at mercy of bandwidth limitation, eh?

**Comment by nevyn** [comment]
@bjornbytes Done, git LFS removed from `oculus-mobile`. It was only used for VrSamples anyway, which is not something that is needed for a submo that provides CI support.

**Comment by bjornbytes** [comment]
Awesome, thanks!

**Comment by nevyn** [comment]
@bjornbytes omg that was fast!! aaahh what a relief, this is finally done!! thank you!! for the first time in years, Alloverse can use pure upstream lovr as-is ;D

**Pull request merged**
