### PR TITLE
Move vector rotate/transform to Vec3/4; Breaks API

### PR DESCRIPTION
**Pull request by jmiskovic**
As discussed in #344, the `Mat4:mul(Vec3)` and `Quat:mul(Vec3)` don't
follow the convention of vector library. Those forms mutate the passed
in vector and not the Mat4/Quat object on which method was called.

The `Mat4:mul(Vec3/4)` is moved to `Vec3/4:transform(Mat4)` and the
`Quat:mul(Vec3)` is moved to `Vec3:rotate(Quat)`.

The `Mat4:mul(x,y,z)` seemed like useful form, and it returns number
components without mutation. That form is now expanded to more useful
`Mat4:mul(x,y,z,w)` to be able to treat input vector as directional.
If not supplied, w defaults to 1 so that vector is treated as point. The
function now returns also the w component.

Because Mat4 has `mul(x,y,z,w)`, the similar form is added to Quat for
consistency: `Quat:mul(x,y,z)`.

This change breaks backward compatibility by removing three forms
`Mat4:mul(Vec3)`, `Mat4:mul(Vec4)` and `Quat:mul(Vec3)`.

Because this is a breaking change, maybe we should update docs, examples and the showcase code to be ready before this is actually merged in.

### CODE REVIEW

**Comment by bjornbytes** [comment]
Still thinking about #169 -- if add/sub/mul/div returned new vectors (potentially with out-args to keep mutation possible), then everything would be consistent: `Mat4:mul(x, y, z, [w])`/`Mat4:mul(v)` and `Vec3:add()` could all return temp vectors.  That would be a huuuge breaking change though.  It's not something immediately relevant to this PR, and I think this PR does a nice job of making things consistent under the current vector system.  Just something I am keeping in mind.

**Comment by jmiskovic** [comment]
This proposal would take care of `Mat4:mul(Vec3)` mutating the vec3 instead of mat4, but the other issue is that `mul` performs semantically different operations. I would still rather apply rotation to the vector, instead of passing vector to quat.

**Comment by bjornbytes** [comment]
I changed the merge base to `dev` since this is a breaking change.

**Comment by jmiskovic** [comment]
If you are still considering this PR, I'd like modify it so that no API is broken. I would just add the new methods and keep the `Mat4:mul(Vec3)`, `Mat4:mul(Vec4)` and `Quat:mul(Vec3)` around. It makes sense that M x V multiplication can be found under `mat4:mul(vec3)`.

We could also add a warning note in docs about possible confusion.

**Comment by bjornbytes** [comment]
Ok here is a slightly modified plan:

- Add `Vec3/Vec4:transform` as in this PR, except using `luax_readmat4` so numbers can be used as well.
- Add `Vec3:rotate` as in this PR, except using `luax_readquat` so angle/axis numbers can be used as well.

This is an easy non-breaking change.  I'll rebase and commit this.

---

For `Mat4/Quat:mul(vec)`, right now they are the only operation `x:op(y)` that modifies `y` and it's surprising/confusing.  I think they should either return numbers or temp vectors.  (Also I think `Quat:mul(x, y, z)` is missing and should be added).

How to decide between vector/number return type?

- number: saves you a temp vector and function call if you were going to immediately `:unpack`
- vector: saves you a function call and `:set` overhead if you were going to use as vector

`Mat4:mul(x, y, z)` returns numbers currently, but there is also `Quat:direction` that returns a temp vec3.  There are also `Mat4:getTranslation/Rotation/Scale` which return numbers, but I think numbers are required here so e.g. `Mat4:getPose` can be added in the future.

I kind of lean towards temp vector return type, since it seems more likely that you're going to use the result for more vector operations, and the cost of unpacking is a little smaller than the cost of :set.

**Comment by bjornbytes** [comment]
Pushed the rest.  Longest PR ever!

**Pull request closed without merging**
