### PR TITLE
lovr.log

### PR DESCRIPTION
**Pull request by bjornbytes**
#177

### CODE REVIEW

**Comment by mcclure** [comment]
I'm definitely happy to have log back in the C code. I have been manually adding lovrLog to basically all of my branches so I can printf debug.

Questions

1. Can `print` be a forward to one of the log levels?
2. In the long run should it be possible to specify which log levels to use? Like, maybe it would be cool if you could say "display logs at LOG_INFO level or above" with a command line option or in `lovr.conf`.

**Comment by bjornbytes** [comment]
1. I was planning on not overriding the default `print` function anymore.  There are a few other places where we kinda augment built-in Lua behaviors (math.random, require) and we don't do overrides there.  Projects would then need to do `print = lovr.log` or just not use `print`.  Although this approach feels like the "right" thing to do, I am still thinking about it because the convenience of automatically overriding print is pretty big.
2. It's a possibility.  It seems easy enough to override `lovr.log` to add whatever kind of filtering you want, but yeah the log level filtering is probably the most common one that would make sense to have a built in flag for.

**Comment by mcclure** [comment]
`Projects would then need to do print = lovr.log or just not use print` I cannot express how much I oppose this idea. "print" is Lua. People will just haul off and use "print", besides which libraries probably use "print". If it's there people will use it and then they'll be sitting there trying to figure out why it works on PC but doesn't work on the oculus target

**Comment by bjornbytes** [comment]
I gotta think more about this before continuing, I actually really like the simplicity of Lua's new `warn` function compared to multiple log levels, but it would need to be polyfilled for older Lua versions and it doesn't provide an immediate solution for non-warn prints.

**Pull request closed without merging**
